NetCoreCRUDAjax/Models/Transaction.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreCRUDAjax.Models
{
    public class Transaction
    {
        [Key]
        public int Id { get; set; }

        [Column(TypeName = "varchar(10)")]
        [DisplayName("Numero de cuenta")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [MaxLength(10)]
        public string AccountNumber { get; set; }
        
        [Column(TypeName = "varchar(100)")]
        [DisplayName("Beneficiario")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [MaxLength(100)]
        public string BeneficiaryName { get; set; }

        [Column(TypeName = "varchar(30)")]
        [DisplayName("Banco")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [MaxLength(30)]
        public string BankName { get; set; }

        [DisplayName("Fecha")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime TransactionDate { get; set; }

        [Column(TypeName = "decimal(10,2)")]
        [DisplayName("Monto")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public decimal Ammount { get; set; }
    }
}

NetCoreCRUDAjax/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NetCoreCRUDAjax.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreCRUDAjax.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

NetCoreCRUDAjax/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreCRUDAjax.Helper;
using NetCoreCRUDAjax.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreCRUDAjax.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ApplicationDBContext context;

        public TransactionController(ApplicationDBContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var transacciones = await context.Transactions.ToListAsync();
            return View(transacciones);
        }

        [HttpGet]
        [NoDirectAccess]
        public async Task<ActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Transaction());

            var transaccion = await context.Transactions.FirstOrDefaultAsync(x => x.Id == id);
            if (transaccion == null)
                return NotFound();

            return View(transaccion);
        }

        [HttpPost]
        public async Task<ActionResult> AddOrEdit(int id, [FromForm] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                //insert
                if (id == 0)
                {
                    transaction.TransactionDate = DateTime.Now;
                    context.Transactions.Add(transaction);
                    await context.SaveChangesAsync();
                }
                //update
                else
                {
                    context.Transactions.Update(transaction);                    
                    await context.SaveChangesAsync();
                }
                return Json(new { isValid = true, html = RenderRazor.RenderRazorViewToString(this,"_ViewAll",context.Transactions.ToList()) });
            }
            return Json(new { isValid = false, html = RenderRazor.RenderRazorViewToString(this, "AddOrEdit", transaction) });
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var transaccion = await context.Transactions.FirstOrDefaultAsync(x => x.Id == id);
            if (transaccion == null)
                return NotFound();

            return View(transaccion);
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            var transaccion = await context.Transactions.FirstOrDefaultAsync(x => x.Id == id);
            if (transaccion == null)
                return NotFound();

            context.Transactions.Remove(transaccion);
            await context.SaveChangesAsync();
            //return View("Index",await context.Transactions.ToListAsync());
            return Json(new { html = RenderRazor.RenderRazorViewToString(this, "_ViewAll", context.Transactions.ToList()) });
        }
    }
}

NetCoreCRUDAjax/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetCoreCRUDAjax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreCRUDAjax</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCoreCRUDAjax</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--MODAL-->
    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>

    <div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NetCoreCRUDAjax - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/notify.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NetCoreCRUDAjax/Views/Transaction/AddOrEdit.cshtml
@model NetCoreCRUDAjax.Models.Transaction
@{
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this)" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="TransactionDate" />

            <div class="form-group">
                <label asp-for="AccountNumber" class="control-label"></label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">#</div>
                    </div>
                    <input asp-for="AccountNumber" class="form-control" />
                </div>
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="BeneficiaryName" class="control-label"></label>
                        <input asp-for="BeneficiaryName" class="form-control" />
                        <span asp-validation-for="BeneficiaryName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="BankName" class="control-label"></label>
                        <input asp-for="BankName" class="form-control" />
                        <span asp-validation-for="BankName" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Ammount" class="control-label"></label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-dollar-sign"></i></div>
                    </div>
                    <input asp-for="Ammount" class="form-control" />
                </div>
                <span asp-validation-for="Ammount" class="text-danger"></span>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <input type="submit" value="Enviar" class="btn btn-primary btn-block" />
                </div>
            </div>
        </form>

    </div>
</div> 

NetCoreCRUDAjax/Views/Transaction/Index.cshtml
@model IEnumerable<NetCoreCRUDAjax.Models.Transaction>

<h1 class="text-center">Bank Transactions <i class="fas fa-comment-dollar text-success"></i> </h1>

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NetCoreCRUDAjax/Views/Transaction/_ViewAll.cshtml
@model IEnumerable<NetCoreCRUDAjax.Models.Transaction>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(x => x.AccountNumber)
            </th>
            <th>
                @Html.DisplayNameFor(x => x.BeneficiaryName)
            </th>
            <th>
                @Html.DisplayNameFor(x => x.BankName)
            </th>
            <th>
                @Html.DisplayNameFor(x => x.TransactionDate)
            </th>
            <th>
                @Html.DisplayNameFor(x => x.Ammount)
            </th>
            <th>
                <a onclick="showModal('@Url.Action("AddOrEdit","Transaction",new { Id = 0 }, Context.Request.Scheme)', 'Nueva transacción')" class="btn btn-success text-white"><i class="fas fa-random"></i> Nueva Transacción</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.AccountNumber</td>

                    <td>@item.BeneficiaryName</td>

                    <td>@item.BankName</td>

                    <td>@item.TransactionDate</td>

                    <td>@item.Ammount</td>

                    <td>
                        <div class="container text-center">
                            <div class="row">
                                <a onclick="showModal('@Url.Action("AddOrEdit","Transaction",new { Id = item.Id }, Context.Request.Scheme)', 'Editar transacción')" class="btn btn-primary text-white mr-1"><i class="fas fa-pencil-alt"></i> Editar</a>
                                <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this)">
                                    <button type="submit" name="name" class="btn btn-danger"><i class="fas fa-trash"></i> Borrar</button>
                                </form>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>